prop_name_mapping = {
    "Purdue Boilermakers": ['Purdue'],
    "Rhode Island Rams": ['Rhode Island'],
    "UC Irvine Anteaters": ['UC Irvine'],
    "Pittsburgh Panthers": ['Pittsburgh'],
    "Illinois Fighting Illini": ['Illinois'],
    "Seattle Redhawks": ['Seattle'],
    "Maryland Terrapins": ['Maryland'],
    "Navy Midshipmen": ['Navy'],
    "Texas Longhorns": ['Texas'],
    "College of Charleston Cougars":["College of Charleston","Charleston"],
    "Louisiana Tech Bulldogs":["Louisiana Tech"],
    "Toledo Rockets":["Toledo"],
    "Portland Pilots":["Portland"],
    "North Texas Mean Green":["North Texas"],
    "UI Chicago Flames":["UIC", "Illinois-Chicago", "UI Chicago"],
    "Milwaukee Panthers":["Milwaukee", "Wis.-Milwaukee"],
    "UT Martin Skyhawks":["UT Martin", "Tenn-Martin"],
    "Towson Tigers":["Towson"],
    "Miami Redhawks":["Miami (OH)", "Miami Ohio"],
    "UNC Wilmington Seahawks":["UNC Wilmington", "NC-Wilmington"],
    "Florida Gators":["Florida"],
    "Boston College Eagles":["Boston College"],
    "St. Francis Brooklyn Terriers":["St. Francis Brooklyn", 'St. Francis (NY)'],
    "Ohio State Buckeyes":["Ohio State","Ohio St."],
    "Tennessee Tech Golden Eagles":["Tennessee Tech"],
    "North Carolina State Wolfpack":["North Carolina State"],
    "Marshall Thundering Herd":["Marshall"],
    "Georgetown Hoyas":["Georgetown"],
    "Old Dominion Monarchs":["Old Dominion"],
    "Virginia Cavaliers":["Virginia"],
    "William & Mary Tribe":["William & Mary"],
    "VMI Keydets":["VMI"],
    "Stony Brook Seawolves":["Stony Brook"],
    "Connecticut Huskies":["Connecticut"],
    "Stetson Hatters":["Stetson"],
    "Wake Forest Demon Deacons":["Wake Forest"],
    "Citadel Bulldogs":["Citadel"],
    "Richmond Spiders":["Richmond"],
    "Columbia Lions":["Columbia"],
    "La Salle Explorers":["La Salle"],
    "Lipscomb Bison":["Lipscomb"],
    "North Carolina Tarheels":["North Carolina"],
    "Liberty Flames":["Liberty"],
    "North Carolina Central Eagles":["North Carolina Central"],
    "Morehead State Eagles":["Morehead State"],
    "Campbell Fighting Camels":["Campbell"],
    "Virginia Tech Hokies":["Virginia Tech"],
    "UNC Greensboro Spartans":["NC-Greensboro","UNC Greensboro"],
    "VCU Rams":["VCU"],
    "East Carolina Pirates":["East Carolina"],
    "Seton Hall Pirates":["Seton Hall"],
    "Temple Owls":["Temple"],
    "Penn State Nittany Lions":["Penn State", "Penn St."],
    "Saint Francis Red Flash":["St. Francis (PA)","Saint Francis"],
    "American Eagles":["American U.","American"],
    "Mississippi Valley State Delta Devils":["Mississippi Valley State"],
    "Georgia Bulldogs":["Georgia"],
    "Georgia Tech Yellow Jackets":["Georgia Tech"],
    "Charleston Southern Buccaneers":["Charleston Southern"],
    "Kennesaw State Owls":["Kennesaw St.","Kennesaw State"],
    "Bradley Braves":["Bradley"],
    "Savannah State Tigers":["Savannah State"],
    "Stephen F. Austin Lumberjacks":["Stephen F. Austin"],
    "Nicholls Colonels":["Nicholls State","Nicholls"],
    "Houston Cougars":["Houston"],
    "UT Arlington Mavericks":["Texas-Arlington","UT Arlington"],
    "North Dakota Fighting Hawks":["North Dakota"],
    "UL Monroe Warhawks":["UL Monroe", "Louisiana-Monroe"],
    "Texas Tech Red Raiders":["Texas Tech"],
    "Tennessee State Tigers":["Tennessee State", "Tennessee St."],
    "Mississippi State Bullldogs":["Mississippi State", "Mississippi St."],
    "Longwood Lancers":["Longwood"],
    "Kansas Jayhawks":["Kansas"],
    "Brown Bears":["Brown"],
    "Fordham Rams":["Fordham"],
    "Middle Tennessee State Blue Raiders":["Middle Tennessee State", "Middle Tennessee St."],
    "Western Illinois Leathernecks":["Western Illinois"],
    "Eastern Illinois Panthers":["Eastern Illinois"],
    "South Dakota State Jack Rabbits":["South Dakota State"],
    "Arkansas State Red Wolves":["Arkansas State", "Arkansas St."],
    "Mississippi Rebels":["Mississippi", "Ole Miss"],
    "New Mexico State Aggies":["New Mexico State", "New Mexico St."],
    "Alabama State Hornets":["Alabama State", "Alabama St."],
    "Creighton Bluejays":["Creighton"],
    "Louisiana Rajin' Cajuns":["Louisiana", "Louisiana-Lafayette"],
    "Valparaiso Beacons":["Valparaiso"],
    "Georgia Southern Eagles":["Georgia Southern"],
    "Notre Dame Fighting Irish":["Notre Dame"],
    "Eastern Michigan Eagles":["Eastern Michigan"],
    "Michigan State Spartans":["Michigan State", "Michigan St."],
    "St. Bonaventure Bonnies":["St. Bonaventure"],
    "San Jose State Spartans":["San Jose State", "San Jose St."],
    "Canisius Golden Griffins":["Canisius"],
    "Eastern Washington Eagles":["Eastern Washington"],
    "Santa Clara Broncos":["Santa Clara"],
    "California State Bakersfield Roadrunners":["California State Bakersfield", "Cal. State - Bakersfield"],
    "Southern Jaguars":["Southern"],
    "Gonzaga Bulldogs":["Gonzaga"],
    "UT San Antonio Roadrunners":["UT San Antonio", "UTSA", "Texas-San Antonio"],
    "Fresno State Bulldogs":["Fresno State", "Fresno St."],
    "Brigham Young Cougars":["Brigham Young", "BYU"],
    "Oakland Golden Grizzlies":["Oakland"],
    "West Virginia Mountaineers":["West Virginia"],
    "Maine Black Bears":["Maine"],
    "Utah Valley Wolverines":["Utah Valley", "UVU"],
    "Marquette Golden Eagles":["Marquette"],
    "Prairie View A&M Panthers":["Prairie View A&M"],
    "UNC Asheville Bulldogs":["UNC Asheville", "N.C. Asheville"],
    "Auburn Tigers":["Auburn"],
    "Grand Canyon Antelopes":["Grand Canyon"],
    "Utah Utes":["Utah"],
    "Rice Owls":["Rice"],
    "Grambling State Tigers":["Grambling State", "Grambling St."],
    "Baylor Bears":["Baylor"],
    "Oral Roberts Golden Eagles":["Oral Roberts"],
    "Missouri State Bears":["Missouri State", "Missouri St."],
    "Idaho State Bengals":["Idaho State", "Idaho St."],
    "Colorado Buffaloes":["Colorado"],
    "North Dakota State Bison":["North Dakota State", "North Dakota St."],
    "Oregon Ducks":["Oregon"],
    "California State Northridge Matadors":["California State Northridge", "CSU Northridge"],
    "UC Los Angeles Bruins":["UC Los Angeles", "UCLA"],
    "Seattle Redhawks":["Seattle"],
    "San Francisco Dons":["San Francisco"],
    "Montana State Bobcats":["Montana State", "Montana St."],
    "Hawaii Rainbow Warriors":["Hawaii"],
    "Gardner-Webb Runnin' Bulldogs":["Gardner-Webb"],
    "Charlotte 49ers":["Charlotte"],
    "Kent State Golden Flashes":["Kent State", "Kent St."],
    "Iona Gaels":["Iona"],
    "UT Rio Grande Valley Vaqueros":["UT Rio Grande Valley", "UTPA", "Texas-Pan American"],
    "Indiana State Sycamores":["Indiana State", "Indiana St."],
    "Florida Gulf Coast Eagles":["Florida Gulf Coast", "FGCU"],
    "Indiana Hoosiers":["Indiana"],
    "Boston Terriers":["Boston", "Boston University", "Boston U."],
    "Northeastern Huskies":["Northeastern"],
    "Lafayette Leopards":["Lafayette"],
    "Wagner Seahawks":["Wagner"],
    "Northern Iowa Panthers":["Northern Iowa"],
    "Syracuse Orange":["Syracuse"],
    "Army Black Knights":["Army"],
    "UC Davis Aggies":["UC Davis"],
    "Florida Atlantic Owls":["Florida Atlantic", "FAU"],
    "Western Michigan Broncos":["Western Michigan"],
    "Xavier Musketeers":["Xavier"],
    "Tulane Green Wave":["Tulane"],
    "Maryland Eastern Shore Hawks":["Maryland Eastern Shore", "Maryland - E. Shore"],
    "Rutgers Scarlet Knights":["Rutgers"],
    "Princeton Tigers":["Princeton"],
    "East Tennessee State Buccaneers":["East Tennessee State", "East Tennessee St."],
    "Kentucky Wildcats":["Kentucky"],
    "Bowling Green Falcons":["Bowling Green"],
    "Howard Bison":["Howard"],
    "Furman Paladins":["Furman"],
    "Norfolk State Spartans":["Norfolk State", "Norfolk St."],
    "Long Island Sharks":["Long Island", "LIU", "LIU Brooklyn"],
    "Southern Mississippi Golden Eagles":["Southern Mississippi", "Southern Miss"],
    "South Florida Bulls":["South Florida", "USF"],
    "Central Florida Knights":["Central Florida", "UCF"],
    "Mercer Bears":["Mercer"],
    "Samford Bulldogs":["Samford"],
    "Youngstown State Penguins":["Youngstown State", "Youngstown St."],
    "Jacksonville Dolphins":["Jacksonville"],
    "Miami Hurricanes":["Miami", "Miami (FL)", "Miami-Florida"],
    "Cornell Big Red":["Cornell"],
    "Albany Great Danes":["Albany"],
    "Western Kentucky Hilltoppers":["Western Kentucky", "WKU"],
    "Saint Joseph's Hawks":["St. Joseph's", "St. Joseph's"],
    "Denver Pioneers":["Denver"],
    "UC Santa Barbara Gauchos":["UC Santa Barbara"],
    "Coastal Carolina Chanticleers":["Coastal Carolina"],
    "Massachusetts Minutemen":["Massachusetts", "UMass"],
    "Rider Broncs":["Rider"],
    "Cleveland State Vikings":["Cleveland State", "Cleveland St."],
    "Bryant Bulldogs":["Bryant"],
    "Akron Zips":["Akron"],
    "Troy Trojans":["Troy"],
    "Florida International Panthers":["Florida International", "FIU"],
    "Iowa State Cyclones":["Iowa State", "Iowa St."],
    "Northern Arizona Lumberjacks":["Northern Arizona", "NAU"],
    "Nebraska Cornhuskers":["Nebraska"],
    "South Dakota Coyotes":["South Dakota"],
    "Louisiana State Tigers":["Louisiana State", "LSU", "Louisiana St."],
    "Northwestern State Demons":["Northwestern State", "Northwestern St."],
    "Vanderbilt Commodores":["Vanderbilt"],
    "Presbyterian Blue Hose":["Presbyterian"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Montana State Bobcats":["Montana State", "Montana St."],
    "Montana State Bobcats":["Montana State", "Montana St."],
    "Montana State Bobcats":["Montana State", "Montana St."],
    "Montana State Bobcats":["Montana State", "Montana St."],
    "Montana State Bobcats":["Montana State", "Montana St."],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],

}

def normalize_prop_name(name):
    for standard_name, aliases in prop_name_mapping.items():
        if name in aliases:
            return standard_name
    return name  # Return original name if no match is found