prop_name_mapping = {
    "Purdue Boilermakers": ['Purdue'],
    "Rhode Island Rams": ['Rhode Island'],
    "UC Irvine Anteaters": ['UC Irvine'],
    "Pittsburgh Panthers": ['Pittsburgh'],
    "Illinois Fighting Illini": ['Illinois'],
    "Seattle Redhawks": ['Seattle'],
    "Maryland Terrapins": ['Maryland'],
    "Navy Midshipmen": ['Navy'],
    "Texas Longhorns": ['Texas'],
    "College of Charleston Cougars":["College of Charleston","Charleston"],
    "Louisiana Tech Bulldogs":["Louisiana Tech"],
    "Toledo Rockets":["Toledo"],
    "Portland Pilots":["Portland"],
    "North Texas Mean Green":["North Texas"],
    "UIC Flames":["UIC", "Illinois-Chicago"],
    "Milwaukee Panthers":["Milwaukee", "Wis.-Milwaukee"],
    "UT Martin Skyhawks":["UT Martin", "Tenn-Martin"],
    "Towson Tigers":["Towson"],
    "Miami Redhawks":["Miami (OH)"],
    "UNC Wilmington Seahawks":["UNC Wilmington", "NC-Wilmington"],
    "Florida Gators":["Florida"],
    "Boston College Eagles":["Boston College"],
    "St. Francis Brooklyn Terriers":["St. Francis Brooklyn", 'St. Francis (NY)'],
    "Ohio State Buckeyes":["Ohio State","Ohio St."],
    "Tennessee Tech Golden Eagles":["Tennessee Tech"],
    "North Carolina State Wolfpack":["North Carolina State"],
    "Marshall Thundering Herd":["Marshall"],
    "Georgetown Hoyas":["Georgetown"],
    "Old Dominion Monarchs":["Old Dominion"],
    "Virginia Cavaliers":["Virginia"],
    "William & Mary Tribe":["William & Mary"],
    "VMI Keydets":["VMI"],
    "Stony Brook Seawolves":["Stony Brook"],
    "Connecticut Huskies":["Connecticut"],
    "Stetson Hatters":["Stetson"],
    "Wake Forest Demon Deacons":["Wake Forest"],
    "Citadel Bulldogs":["Citadel"],
    "Richmond Spiders":["Richmond"],
    "Columbia Lions":["Columbia"],
    "La Salle Explorers":["La Salle"],
    "Lipscomb Bison":["Lipscomb"],
    "North Caroliina Tarheels":["North Caroliina"],
    "Liberty Flames":["Liberty"],
    "North Carolina Central Eagles":["North Carolina Central"],
    "Morehead State Eagles":["Morehead State"],
    "Campbell Fighting Camels":["Campbell"],
    "Virginia Tech Hokies":["Virginia Tech"],
    "UNC Greensboro Spartans":["NC-Greensboro","UNC Greensboro"],
    "VCU Rams":["VCU"],
    "East Carolina Pirates":["East Carolina"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],

}

def normalize_prop_name(name):
    for standard_name, aliases in prop_name_mapping.items():
        if name in aliases:
            return standard_name
    return name  # Return original name if no match is found