prop_name_mapping = {
    "Purdue Boilermakers": ['Purdue'],
    "Rhode Island Rams": ['Rhode Island'],
    "UC Irvine Anteaters": ['UC Irvine'],
    "Pittsburgh Panthers": ['Pittsburgh'],
    "Illinois Fighting Illini": ['Illinois'],
    "Seattle Redhawks": ['Seattle'],
    "Maryland Terrapins": ['Maryland'],
    "Navy Midshipmen": ['Navy'],
    "Texas Longhorns": ['Texas'],
    "College of Charleston Cougars":["College of Charleston","Charleston"],
    "Louisiana Tech Bulldogs":["Louisiana Tech"],
    "Toledo Rockets":["Toledo"],
    "Portland Pilots":["Portland"],
    "North Texas Mean Green":["North Texas"],
    "UI Chicago Flames":["UIC", "Illinois-Chicago", "UI Chicago"],
    "Milwaukee Panthers":["Milwaukee", "Wis.-Milwaukee"],
    "UT Martin Skyhawks":["UT Martin", "Tenn-Martin"],
    "Towson Tigers":["Towson"],
    "Miami Redhawks":["Miami (OH)"],
    "UNC Wilmington Seahawks":["UNC Wilmington", "NC-Wilmington"],
    "Florida Gators":["Florida"],
    "Boston College Eagles":["Boston College"],
    "St. Francis Brooklyn Terriers":["St. Francis Brooklyn", 'St. Francis (NY)'],
    "Ohio State Buckeyes":["Ohio State","Ohio St."],
    "Tennessee Tech Golden Eagles":["Tennessee Tech"],
    "North Carolina State Wolfpack":["North Carolina State"],
    "Marshall Thundering Herd":["Marshall"],
    "Georgetown Hoyas":["Georgetown"],
    "Old Dominion Monarchs":["Old Dominion"],
    "Virginia Cavaliers":["Virginia"],
    "William & Mary Tribe":["William & Mary"],
    "VMI Keydets":["VMI"],
    "Stony Brook Seawolves":["Stony Brook"],
    "Connecticut Huskies":["Connecticut"],
    "Stetson Hatters":["Stetson"],
    "Wake Forest Demon Deacons":["Wake Forest"],
    "Citadel Bulldogs":["Citadel"],
    "Richmond Spiders":["Richmond"],
    "Columbia Lions":["Columbia"],
    "La Salle Explorers":["La Salle"],
    "Lipscomb Bison":["Lipscomb"],
    "North Carolina Tarheels":["North Carolina"],
    "Liberty Flames":["Liberty"],
    "North Carolina Central Eagles":["North Carolina Central"],
    "Morehead State Eagles":["Morehead State"],
    "Campbell Fighting Camels":["Campbell"],
    "Virginia Tech Hokies":["Virginia Tech"],
    "UNC Greensboro Spartans":["NC-Greensboro","UNC Greensboro"],
    "VCU Rams":["VCU"],
    "East Carolina Pirates":["East Carolina"],
    "Seton Hall Pirates":["Seton Hall"],
    "Temple Owls":["Temple"],
    "Penn State Nittany Lions":["Penn State", "Penn St."],
    "Saint Francis Red Flash":["St. Francis (PA)","Saint Francis"],
    "American Eagles":["American U.","American"],
    "Mississippi Valley State Delta Devils":["Mississippi Valley State"],
    "Georgia Bulldogs":["Georgia"],
    "Georgia Tech Yellow Jackets":["Georgia Tech"],
    "Charleston Southern Buccaneers":["Charleston Southern"],
    "Kennesaw State Owls":["Kennesaw St.","Kennesaw State"],
    "Bradley Braves":["Bradley"],
    "Savannah State Tigers":["Savannah State"],
    "Stephen F. Austin Lumberjacks":["Stephen F. Austin"],
    "Nicholls Colonels":["Nicholls State","Nicholls"],
    "Houston Cougars":["Houston"],
    "UT Arlington Mavericks":["Texas-Arlington","UT Arlington"],
    "North Dakota Fighting Hawks":["North Dakota"],
    "UL Monroe Warhawks":["UL Monroe", "Louisiana-Monroe"],
    "Texas Tech Red Raiders":["Texas Tech"],
    "Tennessee State Tigers":["Tennessee State", "Tennessee St."],
    "Mississippi State Bullldogs":["Mississippi State", "Mississippi St."],
    "Longwood Lancers":["Longwood"],
    "Kansas Jayhawks":["Kansas"],
    "Brown Bears":["Brown"],
    "Fordham Rams":["Fordham"],
    "Middle Tennessee State Blue Raiders":["Middle Tennessee State", "Middle Tennessee St."],
    "Western Illinois Leathernecks":["Western Illinois"],
    "Eastern Illinois Panthers":["Eastern Illinois"],
    "South Dakota State Jack Rabbits":["South Dakota State"],
    "Arkansas State Red Wolves":["Arkansas State", "Arkansas St."],
    "Mississippi Rebels":["Mississippi", "Ole Miss"],
    "New Mexico State Aggies":["New Mexico State", "New Mexico St."],
    "Alabama State Hornets":["Alabama State", "Alabama St."],
    "Creighton Bluejays":["Creighton"],
    "Louisiana Rajin' Cajuns":["Louisiana", "Louisiana-Lafayette"],
    "Valparaiso Beacons":["Valparaiso"],
    "Georgia Southern Eagles":["Georgia Southern"],
    "Notre Dame Fighting Irish":["Notre Dame"],
    "Eastern Michigan Eagles":["Eastern Michigan"],
    "Michigan State Spartans":["Michigan State", "Michigan St."],
    "St. Bonaventure Bonnies":["St. Bonaventure"],
    "San Jose State Spartans":["San Jose State", "San Jose St."],
    "Canisius Golden Griffins":["Canisius"],
    "Eastern Washington Eagles":["Eastern Washington"],
    "Santa Clara Broncos":["Santa Clara"],
    "California State Bakersfield Roadrunners":["California State Bakersfield", "Cal. State - Bakersfield"],
    "Southern Jaguars":["Southern"],
    "Gonzaga Bulldogs":["Gonzaga"],
    "UT San Antonio Roadrunners":["UT San Antonio", "UTSA", "Texas-San Antonio"],
    "Fresno State Bulldogs":["Fresno State", "Fresno St."],
    "Brigham Young Cougars":["Brigham Young", "BYU"],
    "Oakland Golden Grizzlies":["Oakland"],
    "West Virginia Mountaineers":["West Virginia"],
    "Maine Black Bears":["Maine"],
    "Utah Valley Wolverines":["Utah Valley", "UVU"],
    "Marquette Golden Eagles":["Marquette"],
    "Prairie View A&M Panthers":["Prairie View A&M"],
    "UNC Asheville Bulldogs":["UNC Asheville", "N.C. Asheville"],
    "Auburn Tigers":["Auburn"],
    "Grand Canyon Antelopes":["Grand Canyon"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],

}

def normalize_prop_name(name):
    for standard_name, aliases in prop_name_mapping.items():
        if name in aliases:
            return standard_name
    return name  # Return original name if no match is found