temp = {
    "Utah Utes":["Utah"],
    "Rice Owls":["Rice"],
    "Grambling State Tigers":["Grambling State", "Grambling St."],
    "Baylor Bears":["Baylor"],
    "Oral Roberts Golden Eagles":["Oral Roberts"],
    "Missouri State Bears":["Missouri State", "Missouri St."],
    "Idaho State Bengals":["Idaho State", "Idaho St."],
    "Colorado Buffaloes":["Colorado"],
    "North Dakota State Bison":["North Dakota State", "North Dakota St."],
    "Oregon Ducks":["Oregon"],
    "California State Northridge Matadors":["California State Northridge", "CSU Northridge"],
    "UC Los Angeles Bruins":["UC Los Angeles", "UCLA"],
    "Seattle Redhawks":["Seattle"],
    "San Francisco Dons":["San Francisco"],
    "Montana State Bobcats":["Montana State", "Montana St."],
    "Hawaii Rainbow Warriors":["Hawaii"],
    "Gardner-Webb Runnin' Bulldogs":["Gardner-Webb"],
    "Charlotte 49ers":["Charlotte"],
    "Kent State Golden Flashes":["Kent State", "Kent St."],
    "Iona Gaels":["Iona"],
    "UT Rio Grande Valley Vaqueros":["UT Rio Grande Valley", "UTPA", "Texas-Pan American"],
    "Indiana State Sycamores":["Indiana State", "Indiana St."],
    "Florida Gulf Coast Eagles":["Florida Gulf Coast", "FGCU"],
    "Indiana Hoosiers":["Indiana"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    "Toledo":["Toledo"],
    
}