# Generated by Django 5.0 on 2024-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('conference', models.CharField(max_length=80)),
                ('rating', models.IntegerField()),
                ('o_rating', models.IntegerField()),
                ('d_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('team', models.CharField(max_length=80)),
                ('conference', models.CharField(max_length=80)),
                ('rating', models.IntegerField()),
                ('o_rating', models.IntegerField()),
                ('d_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('team', models.CharField(max_length=80)),
                ('conference', models.CharField(max_length=80)),
                ('rating', models.IntegerField()),
                ('o_rating', models.IntegerField()),
                ('d_rating', models.IntegerField()),
            ],
        ),
    ]
