# Generated by Django 5.0 on 2024-04-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceranking',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='playerranking',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='teamranking',
            name='rank',
        ),
    ]
